project:
  type: website

website:
  title: "{{< var jpe.short >}} Data Editor"
  favicon: img/jpeicon.png
  page-footer: 
    left: "{{< var jpe.short >}} Data Editor: [{{< var de.mail >}}]({{< var de.mail >}}) <br> {{< var jpe.short >}} Journal Office: [{{< var jpe.mail >}}]({{< var jpe.mail >}})"
    center: "© [Florian Oswald](https://floswald.github.io) {{< var de.year >}}"
    right:
      - icon: github
        href: https://github.com/jpedataeditor

  # temporary
  announcement: 
    icon: cone-striped
    dismissable: false
    content: "This website is being built at the moment. Official Launch July 1st 2025."
    type: warning
    position: above-navbar

  sidebar:
    style: docked
    logo: img/jpe.jpg
    alignment: left
    contents: 
      - href: index.qmd
        text: Home     
      - href: policy.qmd
        text: Code and Data Policy      
      - href: before.qmd
        text: Before Submission 
      - href: package.qmd
        text: Preparing the Package
      - href: best.qmd
        text: Best Practice     
      - href: faqs.qmd
        text: FAQs
      - href: de.qmd
        text: Data Editor
      
  google-analytics:
    tracking-id: "G-48S9X9V28L"
    anonymize-ip: true
  cookie-consent: true

format:
  html:
    mermaid:
      theme: default
    theme: 
      # - cosmo
      - mytheme.scss
    toc: true



