project:
  type: website

website:
  title: "JPE Data Editor"
  favicon: img/jpeicon.png
  repo-url: https://github.com/jpedataeditor/jpedataeditor.github.io
  page-footer: 
    left: "JPE Data Editor: [jpe.dataeditor@gmail.com](mailto:jpe.dataeditor@gmail.com) <br> JPE Journal Office: [jpe@press.uchicago.edu](mailto:jpe@press.uchicago.edu)"
    center: "© [Florian Oswald](https://floswald.github.io) {{< var de.year >}}"
    right: "[Report an Issue](https://github.com/jpedataeditor/jpedataeditor.github.io/issues/new/choose)"

  # temporary
  announcement: 
    icon: cone-striped
    dismissable: false
    content: "This website is being built at the moment. Official Launch July 1st 2025."
    type: warning
    position: above-navbar

  sidebar:
    style: docked
    logo: img/jpe.jpg
    alignment: left
    contents: 
      - href: index.qmd
        text: Home     
      - href: policy.qmd
        text: Code and Data Policy      
      - href: before.qmd
        text: Before Submission 
      - href: package.qmd
        text: Preparing the Package
      - href: best.qmd
        text: Best Practice     
      - href: faqs.qmd
        text: FAQs
      - href: de.qmd
        text: Data Editor
      
  google-analytics:
    tracking-id: "G-098M22QPXE"
    anonymize-ip: true

  cookie-consent:
    style: simple  # or 'basic' or 'advanced'
    type: implied  # or 'explicit'
    palette: light  # or 'light'
    policy-url: https://jpedataeditor.github.io/privacy.html

format:
  html:
    mermaid:
      theme: neutral
    theme: 
      # - cosmo
      - mytheme.scss
    toc: true



