---
title: JPE Third Party Replication Agreement
date: today
format:
    docx: default
---

This declaration is to certify that


Firstname: _________________________

Lastname: __________________________

Employed at: __________________________

Position: __________________________

is acting as a third party replicator for Journal of Political Economy to verify the results of the paper __________________ [TITLE] by _________________ [AUTHOR(S)]

The third party replicator hereby certifies the following to the Journal of Political Economy:

- [ ] I am not a coauthor of the above-named paper.
- [ ] I am not subject to other conflicts of interest regarding the integrity of the above-named paper.
- [ ] I will execute the data replication check strictly in accordance with the instructions included in the replication package supplied by JPE, without changing any parts of the source code, except where explicitly instructed otherwise by JPE.
- [ ] I will treat all materials (including the JPE replication package) provided to me for the replication checks and the results of the replication checks as strictly confidential, and I will discard any copy of such materials from my computer and any storage devices upon completion.


Date:


Signature: _________________
